-- Neria, drawn by hand as explicit local pixel maps. No rasterisation of
-- vectors, reference tracing, model generation, or downsampling to make art.
-- Coordinates are zero-based. Dots are transparent. Each local map is padded
-- into a full 64x64 layer before image:drawPixel is called.
local revision = tonumber(app.params['revision'] or '4')
local colors = {
 {'O','303C53','deep blue outline / navy shadow'},
 {'h','718391','cool hair outline'},
 {'s','A7B8C2','hair shadow'},
 {'m','D8DEDD','hair mid'},
 {'w','FFF6E6','hair highlight / warm cloth light / eye glint'},
 {'a','83BDCA','aqua hair tip'},
 {'b','568BA3','aqua shadow'},
 {'i','C0E1DF','aqua light'},
 {'k','A7767C','warm face contour'},
 {'p','DDA391','skin shadow'},
 {'f','F5C7AA','skin middle'},
 {'l','FFE3C3','skin light'},
 {'r','E99694','cheek blush'},
 {'e','4D4C61','upper lashes'},
 {'v','4B7D9D','blue-grey iris'},
 {'u','91C5D4','iris light'},
 {'c','E6E3D6','warm white cloth'},
 {'d','AFBEC8','cloth shade'},
 {'n','425D79','navy cloth'},
 {'t','63849C','navy light'},
 {'B','337F9F','cerulean wave'},
 {'C','65AEC0','wave light'},
 {'g','8C8073','antique trim shadow'},
 {'G','D0BE96','antique trim light'},
 {'R','C67D74','coral accent shade'},
 {'T','EFAC8F','coral accent light'},
}
local rgba={['.']=0}
local palette=Palette(#colors+1)
palette:setColor(0,Color{r=0,g=0,b=0,a=0})
local pf=io.open('palette.txt','w')
pf:write('NERIA palette: 26 opaque colours + transparent.\nSample evidence: scripts/source_samples.txt (Aseprite Image:getPixel).\n\n')
pf:write('Adjustment: warm hair #E3DCD8 -> ivory #FFF6E6 and cool #D8DEDD;\n#CBC5C2 -> #A7B8C2 shadow; aqua #B0C2C4 -> #83BDCA/#C0E1DF;\nskin #ECD6CB/#EAD0C3 -> #FFE3C3/#F5C7AA;\nnavy #353C49/#3B4958 -> #303C53/#425D79;\nblue-grey #60707E/#7F848A -> #63849C/#4B7D9D and cerulean #337F9F;\ncloth #EAE4DE -> #FFF6E6/#E6E3D6; trim #9E9189 -> #D0BE96;\ncoral #B77766 -> #C67D74/#EFAC8F. Semantic labels of raw point samples\nare approximate; palette decisions also use direct visual inspection.\n\n')
for idx,c in ipairs(colors) do
 local r,g,b=tonumber(c[2]:sub(1,2),16),tonumber(c[2]:sub(3,4),16),tonumber(c[2]:sub(5,6),16)
 rgba[c[1]]=app.pixelColor.rgba(r,g,b,255)
 palette:setColor(idx,Color{r=r,g=g,b=b,a=255})
 pf:write(c[1],' #',c[2],' ',c[3],'\n')
end
pf:close()
local specs={}
local function block(name,x,y,rows)
 local parsed={}
 for row in rows:gmatch('[^\r\n]+') do parsed[#parsed+1]=row end
 specs[#specs+1]={name=name,x=x,y=y,rows=parsed}
end

block('hair-back',17,6,[[
..........hhhhhhhhhh...........
.......hhhmmmmmmmmmshh.........
......hmmwwwwwwwwmmsssh........
.....hmwwwwwwwwwwmmmsssh.......
....hmwwwwwwwwwwwwmmssshh......
...hmwwwwwwwwwwwwwmmmsssh......
...hmwwwwwwwwwwwwwwmmssshh.....
..hmwwwwwwwwwwwwwwwmmmsssh.....
..hmwwwwwwwwwwwwwwwwmmsssh.....
.hhmwwwwwwwwwwwwwwwwmmssshh....
.hmmwwwwwwwwwwwwwwwwmmssssh....
.hmmwwwwwwwwwwwwwwwwmmssssh....
.hmmwwwwwwwwwwwwwwwwmmssssh....
.hmmwwwwwwwwwwwwwwwwmmssssh....
.hmmwwwwwwwwwwwwwwwwmmssssh....
.hmmwwwwwwwwwwwwwwwwmmssssh....
.hmmwwwwwwwwwwwwwwwwmmssssh....
.hmmwwwwwwwwwwwwwwwwmmssssh....
.hmmwwwwwwwwwwwwwwwwmmssssh....
.hmmwwwwwwwwwwwwwwwwmmssssh....
.hmmwwwwwwwwwwwwwwwwmmssssh....
.hmmwwwwwwwwwwwwwwwwmmssssh....
.hmmwwwwwwwwwwwwwwwwmmssssh....
.hmmwwwwmssmmmmwwwwmmssssh.....
.hmmwwwmsshssmmmwwwmmssssh.....
.hmmwwwmsshssmmmwwwmmssssh.....
.hmmwwwmsshssmmmwwwmmssssh.....
.hmmwwwmsshssmmmwwwmmssssh.....
.hmmwwwmsshssmmmwwwmmssssh.....
.hmmwwwmsshssmmmwwwmmssssh.....
.hmmwwwmsshssmmmwwwmmssssh.....
.hmmwiimsshssmmmwiimmssssh.....
.hmmiimssh.ssmmmiimmssssh.....
.hmiiaassh.ssmmiiimmssssh.....
.hmiiaash..ssmmiiaamssssh.....
.hmiiaash..ssmiiaaamssssh.....
.hmiiaabh..ssmiiaaamsssh......
.hmiiaabh..ssmiiaaamsssh......
.hmiiaabh..ssmiiaaamssh.......
..haiabh...ssmiiaamssh........
..haabh....ssmiaamssh.........
...bh......hsaamssh..........
............hsshh............
]])

block('body',25,25,[[
.....kffffpk........
.....kfffppk........
.....kffpppk........
....kkkkkkkk.......
...OnnntnnnO.......
..OnnntttnnnO......
.OnnntttttnnnO.....
.OnnntttttnnnO.....
.OnnntttttnnnO.....
.OnnntttttnnnO.....
.OnnntttttnnnO.....
.OnnntttttnnnO.....
.OnnntttttnnnO.....
.OnnntttttnnnO.....
.OnnntttttnnnO.....
.OnnntttttnnnO.....
.OnnntttttnnnO.....
.OnnntttttnnnO.....
.OnnntttttnnnO.....
.OnttttnntttnnO....
.OnnttnOnnttnnO....
.OnnnnO.OnnnnnO....
..kkkk...kkkkk.....
..kllf...kllffk....
..kllf...kllfpk....
..klff...kllfpk....
..kfff...klffpk....
..OnnO...OnnnnO....
..OcwO...OcwwdO....
..OcwO...OcwwdO....
..OcwO...OcwwdO....
..OBnO...OcnndO....
..OBnO...OnnndO....
.OdwnO...OdwwnnO...
.OcwnnO..OcwwwdnO..
OwwcnnnO.OwwccddnO.
OnnnnnnO.OnnnnnnnO.
]])

block('outfit',21,28,[[
.........OnGnO...........
........OntGnO...........
......OOnnnnnOO..........
....OOcOnnntOccOO........
...OccwOncccOccddO.......
..OcwwwOnwwwOccdddO......
..OcwwcOnwwwOnBcddO......
.OcwwwdOnwwwOnCCddO......
.OcwwcdOnwwwcOnBddO......
.OcwccdOncccccOnndO......
.OccddOnOnnnnnOnndO......
..OOOOnnnGGnnnnOOO.......
.....OnnnGGnnnnO.........
.....OnnnnnnnnnO.........
....OccOnnnnnnnO.........
....OcwOntttnnnO.........
....OcwOntttnnnO.........
...OccwOnntnnnnO.........
...OcwwOnnnOnnnO.........
...OcwwOnnOOnnnO.........
...OcwwdOOO.OOOO.........
..OccwwdO................
..OcwwBdO................
..OcwBBdO................
..OcBCBdO................
..OcBCwdO................
.OccBBwdO................
.OcwwBddO................
.OcBBcddO................
.OgGGGgO.................
..OOOOO..................
]])

block('face',24,15,[[
....kkkkkkkkkkkk.....
...klllllllllllfk....
..kllllllllllllffk...
.klllllllllllllffpk..
kffllllllllllllffpk..
kpfllllllllllllffpk..
kpfleeeeellleeelfpk..
.kflewvvellwevelfpk..
.kfllevvellvevllfpk..
.kflleuuellvuullfpk..
.kflrrllllllrrlffk...
..kfflllllfllllfpk...
...kfflllllpplffk....
....kpffffffpppk.....
.....kkkkkkkkkk......
]])

block('hair-front',20,7,[[
........hhmmmmmmmh............
.....hhhmmwwwwwwmmhh..........
....hmmwwwwwwwwwwmmsh.........
...hmmwwwwwwwwwwwmmssh........
..hmmwwwwwwwwwwwmmmsssh.......
.hmmwwwwwwwwwwwwmmmsssh.......
.hmmwwwwwwwwwwwmmmssssh.......
hmmwwwwwwwwwwwmmmssmssh.......
hmmwwwwwwwwwmmmmssmmssh.......
hmmwwwwwwwmmmmssmmmwmssh......
hmmwwwwmmmmmmssmmmwwmmsh......
hmmwwwmmmmmmssmmwwwmmmsh......
hmmwwmmmsssssmmwwmmmmsh.......
hmmwwmmsh..hmmmwmmmmsh........
hmmwwmsh...hmmmmmmssh.........
hmmwwmsh....hmmmmshh.......... 
hmmwwmsh.....hmmsh............
hmmwwmsh......hh..............
hmmwwmsh......................
hmmwwmsh..............hmmsh....
hmmwwmsh..............hmmsh....
hmmwwmsh..............hmmsh....
hmmwwmsh..............hmmsh....
hmmwwmsh..............hmmsh....
hmmwwmsh..............hmmsh....
hmmwwmsh..............hmmsh....
hmmwwmsh..............hmmsh....
hmmwwmsh..............hmmsh....
hmmwwmsh..............hmmsh....
hmmwwmsh..............hmmsh....
hmmwimsh..............hmash....
hmiimsh...............hmash....
hmiash................hash....
.haash.................hh.....
..hh.........................
]])

block('keeper-gloves',23,36,[[
...OOO................
..OcwwOO.....OOO......
.OcwwwwdO...OcwdOO....
OntGwwwwdOOOcwwwwdO...
OntGwwwwwwOOwwwwddO...
OntGBBwwwdOOwwBwwdO...
OntGBCBdddOOwBBdddO...
.OnGGBccddOOwBCcddO...
..OOOGGddO.OwccddO....
.....OOOO...OOOOO.....
]])

block('accessories',17,10,[[
.....hh..............
....hBGh.............
..hhBCGh.............
.hGBGhBh.............
hBCGGBGOh............
hGBGGBCOh............
.hBGGBGh.............
..hGBOh..............
..hBBh...............
..hGBh...............
..hCBh...............
..hCBh...............
..hCBh...............
..hCBh...............
..hBBh...............
..hBBh...............
...hh................
]])
block('coral-tassel',42,44,[[
OgO
OGO
.g.
RTR
RTR
RTR
RTR
.R.
]])

-- Revisions are explicit pixel edits, preserved as a reproducible history.
local function change(name,x,y,rows) block(name,x,y,rows) end
local function replace(name,x,y,rows)
 for index,spec in ipairs(specs) do
  if spec.name==name then
   local parsed={};for row in rows:gmatch('[^\r\n]+') do parsed[#parsed+1]=row end
   specs[index]={name=name,x=x,y=y,rows=parsed};return
  end
 end
 error('Layer missing: '..name)
end
if revision>=2 then
 -- Shorten and taper fringe, expose both eyes. Slim the right face framing lock.
 for _,spec in ipairs(specs) do if spec.name=='hair-front' then
  local rows={
   'hmmwwmmmsh..hmmmmmsh...hmsh',
   'hmmwwmmsh....hmmmsh....hmsh',
   'hmmwwmsh......hmsh.....hmsh',
   'hmmwwmsh.......hh......hmsh',
   'hmmwwmsh...............hmsh',
   'hmmwwmsh...............hmsh',
   'hmmwwmsh...............hmsh',
   'hmmwwmsh...............hmsh',
   'hmmwwmsh...............hmsh',
   'hmmwwmsh...............hmsh',
   'hmmwwmsh...............hmsh',
   'hmmwwmsh...............hmsh',
   'hmmwwmsh...............hmsh',
   'hmmwwmsh...............hmsh',
   'hmmwwmsh...............hmsh',
   'hmmwwmsh...............hmsh',
   'hmmwwmsh...............hmsh',
   'hmmwwmsh...............hash',
   'hmmwimsh...............hash',
   'hmiimsh................hash',
   'hmiash..................hh',
   '.haash',
   '..hh',
  }
  for i,row in ipairs(rows) do spec.rows[12+i]=row end
 end end
 replace('face',24,15,[[
....kkkkkkkkkkkk.....
...klllllllllllfk....
..kllllllllllllffk...
.klllllllllllllffpk..
kffllllllllllllffpk..
kpfllllllllllllffpk..
kpflleeeellleeelfpk..
.kfllewvellewvelffpk.
.kfllvuvellevvllffpk.
.kfllvuulllvuullfpk..
.kflrrllllllrrlffk...
..kfflllllfllllfpk...
...kfflllllpplffk....
....kpffffffpppk.....
.....kkkkkkkkkk......
]])
end
if revision>=3 then
 -- Hand anatomy: raised thumbs, broad padded backs and short finger seams.
 replace('keeper-gloves',23,36,[[
......OO................
.....OcwO.......OO......
...OOcwwdOO...OOcwO.....
..OntGwwwwwOOOcwwwdO....
.OntnGBBwwwwwOwcwddO....
.OntnGBCBwdddOwBwwdO....
.OntnGBBwwwwwOwBCddO....
..OntGGcwddddOwBwwdO....
...OOOGGwwwdOOwcddO.....
......OOOOOO..OOOO......
]])
 replace('body',27,43,[[
OnttttttttnnnO...
OnttttttttnnnnO..
OnttttnttttnnnO..
OntttnOntttnnnO..
OnnnnnO..OnnnnnO.
.kllffk..kllffpk.
.kllffk..kllffpk.
.klfffk..klfffpk.
.OnnnnO..OnnnnnO.
.OnGnnO..OnnGnnO.
.OcwcnO..OcwwcnO.
.OcwcnO..OcwwcnO.
.OcwBnO..OcwBcnO.
.OcwBnO..OcBBcnO.
.OnnnnO..OnnnnnO.
OdwwnnO..OdwwnnO.
OcwwwnnO.OcwwwnnnO
OwwccnnO.OwwccddnnO
.OOOOOO...OOOOOOOO
]])
 replace('outfit',21,28,[[
.........OnGnO...........
........OntGnO...........
......OOnnnnnOO..........
....OOcOnnntOccOO........
...OccwOncccOccddO.......
..OcwwwOnwwwOccdddO......
..OcwwcOnwwwOnBcddO......
.OcwwwdOnwwwOnCCddO......
.OcwwcdOnwwwcOnBddO......
.OcwccdOncccccOnndO......
.OccddOnOnnnnnOnndO......
..OOOOnnnGGnnnnOOO.......
.....OnnnGGnnnnO.........
.....OnnnnnnnnnO.........
.....OnnttttnnnnO........
.....OnttttttnnnnO.......
.....OnttttttnnnnO.......
.....OnntttnttnnnO.......
]])
 change('wave-panel',21,44,[[
.....OOO..
....OcwO..
....OcwO..
...OcwwO..
...OcwdO..
...OcwdO..
..OcwwdO..
..OcwBdO..
..OcBBdO..
.OcBCwdO..
.OcBCwdO..
.OcBBwdO..
OcwwBddO..
OcBBcddO..
OgGGGgO...
.OOOOO....
]])
 change('face-expression',31,26,[[
lllllllf
llllkkff
ffffffpp
]])
end
if revision>=4 then
 -- Clear the far iris/glint and let the near sleeve show beside the hair.
 for _,spec in ipairs(specs) do if spec.name=='hair-front' then
  spec.rows[15]='hmmwwmsh......h........hmsh'
  spec.rows[16]='hmmwwmsh...............hmsh'
  for i=22,29 do spec.rows[i]='hmwsh..................hmsh' end
  spec.rows[30]='hmwsh..................hash'
  spec.rows[31]='hmiash.................hash'
  spec.rows[32]='hmiash.................hash'
 end end
 -- Warm-white sleeve fold and navy shoulder braid; connected clusters.
 change('sleeve-trim',24,31,[[
GGOn
wnOn
wcOn
wcOn
cdOn
cdOn
ddOn
]])
 -- Two lower lash colours keep the expression calm; one glint in each eye.
 change('eye-polish',29,21,[[
eeeellleee
ewvelllewve
vuullllvuul
uuulllluul
]])
 -- Small connected lace bars and contrasting white boot toes.
 change('boot-laces',29,58,[[
cnnn....cnnn
wwnc....wwnc
]])
 -- Make the ornament blue with a small warm metal centre.
 change('ornament-polish',18,12,[[
...BCh
.BCGBO
BCGGBG
BGGBBO
.BBGBh
..hBBh
]])
end

local spr=Sprite(64,64,ColorMode.RGB)
spr:setPalette(palette)
local first=true
local flattened=Image(64,64,ColorMode.RGB)
flattened:clear(0)
for _,spec in ipairs(specs) do
 local layer
 if first then layer=spr.layers[1];first=false else layer=spr:newLayer() end
 layer.name=spec.name
 local img=Image(64,64,ColorMode.RGB);img:clear(0)
 for yy,row in ipairs(spec.rows) do
  for xx=1,#row do
   local key=row:sub(xx,xx)
   if key~='.' and key~=' ' then
    assert(rgba[key], 'Unknown pixel '..key)
    local x,y=spec.x+xx-1,spec.y+yy-1
    assert(x>=0 and x<64 and y>=0 and y<64,'Outside canvas')
    img:drawPixel(x,y,rgba[key]);flattened:drawPixel(x,y,rgba[key])
   end
  end
 end
 spr:newCel(layer,1,img,Point(0,0))
end
spr:saveAs('base.aseprite')
flattened:saveAs('base.png')
local bg=app.pixelColor.rgba(139,145,153,255)
local preview=Image(512,512,ColorMode.RGB)
for y=0,511 do for x=0,511 do
 local p=flattened:getPixel(x//8,y//8)
 preview:drawPixel(x,y,app.pixelColor.rgbaA(p)==0 and bg or p)
end end
preview:saveAs('preview_8x.png')
preview:saveAs('scripts/pass_'..revision..'_8x.png')
flattened:saveAs('scripts/pass_'..revision..'.png')
local source=Image{fromFile='source.png'}
local side=Image(864,512,ColorMode.RGB);side:clear(bg)
for y=0,511 do for x=0,340 do side:drawPixel(x,y,source:getPixel(math.min(source.width-1,x*3),y*3)) end end
for y=0,511 do for x=0,511 do side:drawPixel(x+352,y,preview:getPixel(x,y)) end end
side:saveAs('side.png')
print('Rendered revision '..revision..' in Aseprite.')
