-- Neria: hand-authored native 96px pixel maps. No tracing, scaling, or generated art.
-- Run: Aseprite.exe -b --script-param pass=01 --script scripts/draw.lua
local P = {
  N='28364B', n='3C5069', b='526E87', c='6C95AB', d='95BCC7',
  e='C0DFDF', T='537F90',
  H='66778C', h='949EAF', s='BFC6D2', m='DFE1E6', l='F2EFEF', w='FFF9EF',
  a='A5C7CF', q='DAEAE6', S='A8B9C3',
  K='936E7A', k='B6868A', t='D5A39B', u='ECC0AE', v='F6D6C2', f='FFE9D5',
  r='E7A7A6', R='F4BEB6', I='38485F', i='6A94AE', j='A8D7DC', O='F0FAF4',
  x='777575', g='AA9A85', G='D8C8A5', p='B97C76', C='E4A08B',
}
local order='NnbcdeTHhsmlwaqSKktuvfrRIijOxgGpC'
local colors = {}
for key,hex in pairs(P) do
  colors[key]=app.pixelColor.rgba(tonumber(hex:sub(1,2),16),tonumber(hex:sub(3,4),16),tonumber(hex:sub(5,6),16),255)
end
local spr=Sprite(96,96,ColorMode.RGB)
spr.filename='base.aseprite'
local pal=Palette(#order+1)
pal:setColor(0,Color{r=0,g=0,b=0,a=0})
for i=1,#order do
  local h=P[order:sub(i,i)]
  pal:setColor(i,Color{r=tonumber(h:sub(1,2),16),g=tonumber(h:sub(3,4),16),b=tonumber(h:sub(5,6),16),a=255})
end
spr:setPalette(pal)
local current
local first=true
local function layer(name)
  local lay
  if first then lay=spr.layers[1];first=false else lay=spr:newLayer() end
  lay.name=name
  current=Image(96,96,ColorMode.RGB)
  if lay.cels[1] then lay.cels[1].image=current else spr:newCel(lay,1,current,Point(0,0)) end
  -- Cel images are shared through this reference after stamping.
  current=lay.cels[1].image
end
local function map(x,y,rows)
  local yy=0
  for row in rows:gmatch('[^\r\n]+') do
    assert(x+#row<=96,'map outside canvas at '..x..','..y+yy)
    for xx=1,#row do
      local ch=row:sub(xx,xx)
      if ch~='.' and ch~=' ' then
        assert(colors[ch],'undefined palette symbol: '..ch)
        current:drawPixel(x+xx-1,y+yy,colors[ch])
      end
    end
    yy=yy+1
  end
end

layer('01 Hair behind - calm silver and aqua locks')
map(18,24,[[
........HHhhhhhhhhHHHHH
......HHhssmmmmmmssshHHH
.....HhssmmlllllmmsshHHHH
....HhssmmlllllmmsshHhssH
...HhssmmlllllmmsshHhsssH
...HssmmllllllmmssHhssmH
..HhsmlllllllmmsHhssmmH
..HsmlllllllmmssHhssmmH
..HsmllllllmmssHhssmmmH
.HhsmllllllmmssHhssmmmH
.HsmllllllmmssHhssmmmmH
.HsmllllllmmssHhssmmmlH
.HsmllllllmmssHhssmmlmH
.HsmlllllmmssHhssmmmlmH
.HsmlllllmmssHhssmmlmmH
.HsmlllllmmssHhssmmlmmH
.HsmlllllmmssHhssmmlmmH
.HsmllllmmssHhssmmllmmH
.HsmllllmmssHhssmmllmmH
.HsmllllmmssHhssmmllmmH
.HsmllllmmssHhssmmllmmH
.HsmlllmmssHhssmmmllmmH
.HsmlllmmssHhssmmmlmmH
.HsmlllmmssHhssmmmlmmH
.HsmllmmmssHhssmmmlmmH
.HsmllmmmssHhssmmmlmmH
.HsmllmmssHhssmmmlmmH
.HsmllmmssHhssmmmlmmH
.HsmllmmssHhssmmmlmmH
.HsmllmmssHhssmqmlmmH
.HsmllmmssHhssmqqmmH
.HsmllmmssHhssqqqmmH
.HsmlmmmssHhssqqqmmH
.HsmlmmmssHhsaqqqmaH
.HsmqmmssHhsaqqqqaH
.HsmqmmssHhsaqqqqaH
.HsmqqmssHhsaqqqaH
.HsaqqmasHhsaqqqaH
.HsaqqmasHhsaqqdaH
.HsaqqqasHhsaqddaH
.HsaqqqasHhsaqddH
.HsaqqqasHhsaeddH
.HsaqqqasHhsaeddH
.HsaeqqasHhsaeddH
.HsaeqqasHhsaedH
..HaeqqasHhsaedH
..HaeqqasHhsaedH
..HaeqqasHhsaeH
..HdaeqaHhsaeH
...HdeqaHhsaH
...HdeqaHhdH
....HedaHhH
.....HddHH
......HHH
]])
map(61,25,[[
HHHhhhhHHH
HssmmmsshHH
HsmmlllsshHH
HsmllllmsshHH
.HsllllmmsshH
.HslllllmmsshH
.HsmlllllmmshH
..HsmlllllmmshH
..HsmlllllmmshH
..HsmllllllmshH
..HsmllllllmmshH
..HsmllllllmmshH
..HsmllllllmmshH
..HsmmlllllmmshH
..HsmmlllllmmshH
..HsmmlllllmmshH
..HssmlllllmmshH
..HssmlllllmmshH
..HssmlllllmmshH
..HssmlllllmmshH
..HssmlllllmmshH
..HssmlllllmmshH
..HssmllllmmsshH
..HssmllllmmsshH
..HssmllllmmsshH
..HssmlllmmmsshH
..HssmlllmmmsshH
..HssmllmmmmsshH
..HssmllmmmmsshH
..HssmllmmmqshH
..HssmllmmqqshH
..HssmllmqqqshH
..HssmllmqqqshH
..HssmlmqeqashH
..HssmlmqeeashH
..HssmlqqeeashH
..HssmaqqeeashH
..HssmaqqeeashH
..HssmaqqeeashH
..HssmaqqeeashH
..HssmaqqeeashH
..HssmaqqeeashH
..HssmaqqeeashH
...HsmaqqeeashH
...HsmaqqeeashH
...HsmaqqeeashH
...HhsaqeeashH
....HsaqeeashH
....HsaqeashH
.....HsaeashH
.....HhsaahH
......HhshH
.......HHH
]])

layer('02 Side panels - embroidered keeper kit')
map(28,64,[[
........NNNNNNNN
.......NnbbcmmlhH
.......NnblwllmhH
......NnbmwwllshH
......NbmwwwlmshH
.....NnbmwwllmshH
.....NbmwwllmmshH
....NnbmwlllmmshH
....NbmwlllmmshH
....NbmwllcccshH
...NnbmwlcddcshH
...NbmwlcdmmlshH
..NnbmwlccllmshH
..NbmwlmccclshH
..NbmwlcbbcshH
.NnbmwlcbdcshH
.NbmwlcbdcshH
.NbmwlcddclhH
NnbmwllcclhH
NbmwlllmmlhH
NbmwllmmlhH
.NbgGggmhH
..NggggxH
...NNNNH
]])
map(63,63,[[
NNNNNNN
NnblmsH
NncllmsH
NncllmshH
NnblllmsH
NnblllmsH
NnblllmsH
NnbllcmsH
NnbllccsH
NnblcccsH
NnbccmcsH
NnbcmmcsH
NnbcccmsH
NnbbclmsH
NnbcllmsH
NnbcllmsH
.NncllmsH
.NncllmsH
.NncclmsH
..NgGgmsH
..NggggsH
...NNNNHH
]])

map(34,75,[[
..ccc
.cdcc
.cdll
.ccml
..ccc
...cb
..cbb
.ccbb
.ddbc
]])

layer('03 Legs - shorts socks and cleated boots')
map(39,68,[[
..NNNNNNNNNNNNNNNNNNNNNNN
.NnbbbbnnnnbbbbbbbbbbbnnNN
NnbccccbbnnbbbbcccbbbbnnNN
NnbbbccbbnnbbbbccbbbbnnNNN
NnbbbbbbnNNnbbbbbbbbnnNNN
NnbbbbbnNN.NnbbbbbbbnnNN
NnccbbbnN..NnbbbbbbbnnN
NnccbbnNN..NnbccbbbbbNN
NbbbbbnN...NnbcccbbbnN
.NkkttkN....NkkttttkN
.KuvvvkK....KuvvvvutK
.Kuvvvuk....KuvvvvutK
.Kuvvuuk....KuvvvvutK
.NnnnnnN....NnnnnnnnN
.NbggbnN....NnbggbbnN
.NllGgnN....NllGgbbnN
.NwwlbnN....NlwlbbbnN
.NwwlbnN....NlwlbbbnN
.NwlmbnN....NlwlbbbnN
.NwlmbnN....NllmbbbnN
]])
map(35,85,[[
.....NllmbnN
.....NlwlbnN
....NlwmlbnN
...NlwlclbnN
..NwwlcbblnN
.NwwllcllbnN
NwwwwwllmbnN
NnmmllmmbnnN
.NNN....NNN
]])
map(54,85,[[
.NllmbbnN
.NlwlbbnN
.NlwlmbnN
.NlwllmbnNN
.NlwwlmblmlN
.NlwwwlmwwllN
..NwwwwllwwlmN
..NnmllllmmmnN
...NNN....NNN
]])

layer('04 Torso - high collar wave top straps')
map(32,45,[[
...............NNNNNNNN
..............NnbbggbnNN
.............NncbgGgbnnN
..........HHNnbbgnngbnNNH
........HhllNNnbbbbbnNNlwllmllhH
......HhllwwlNNnccnNNllllwwllmshH
....HhllwwwwlbNNNNNbmwllwwllmmshH
...HhlllwwwllbnccclmwlllmwllmmmshH
..HhllwwwlllmbbcllmlwwllmmllmmmsshH
.HhllwwwlllmmnbblwwwlllmmcllccccshH
.HllwwwlllmmNnbllwwllllmccdccddcmshH
HhllwwwlmmshNnblwwllllmccdmcddlllshH
HllwwllmmsH.NnblllmmmcccdmdcllllshH
HllwwllmsH..NnblllmmcddclmclllmmshH
HllwllmmH...NnblllmmcclllcllmmmshH
HllwllmsH...NnnbllmmcccmccmmmmshH
.HlllmshH...NNnnbbllllmmmsssmsHH
.HllmshH....NngGgnnnnnnnbbngGgN
..HsshH.....NnglgnnnnnnnnnnglgN
...HHH......NNggNNNNNNNNNNNggNN
.............NnnbbbbnnbbbbnNNNN
.............NnnbbbbbbbbbbnbnNN
.............NNnbbbbbbbbbbnbnNN
]])
map(63,49,[[
.HhshH
HlllmshH
HlwwlmshH
HlwwllmshH
.HlwwlmshH
.HllwlmshH
..HlllmshH
..HlllmshH
...HlmmshH
...HllshH
....HshH
.....HH
]])
-- Shoulder harness and metal clip, hand-placed map.
map(35,50,[[
...Nnggn
..NngGGgn
.Nnggnngn
NngglsgnN
NnggnngnN
.NnnnnnN
..NnbnN
..NnbnN
..NnbnN
...NnN
]])

layer('05 Face - calm three quarter gaze')
map(36,22,[[
........KKKKKKKKKKKKKKKKKKKKKK
.....KKKttuuuvvvvvvvvvvvvuutttkK
...KKtuuvvffffffffffffffffvvvuuttkK
..KtuuvvffffffffffffffffffffvvvuutkK
.KtuuvvfffffffffffffffffffffvvvutkK
KtuuvvffffffffffffffffffffffvvvutkK
KtuuvvffffffffffffffffffffffvvvutkK
KtuuvvffffffffffffffffffffffvvvutkK
KtuvvvfffffffffffffffffffffvvvvutkK
KtuvvvffffffffffffffffffffvvvvvutkK
KtuvvvfffffffffffffffffffvvvvvvutkK
KtuvvvffffffffffffffffffvvvvvvvutkK
KtuuvvfffffffffffffffffvvvvvvvvvutkK
KtuuvvffffffffffffffffvvvvvvvvvutkK
.KtuuvvffffffffffffffvvvvvvvvvutkK
.KtuuvvfffffffffffffvvvvvvvvvvutkK
..KtuuvvfffffffffffvvvvvvvvvvvutkK
...KtuuvvfffffffffvvvvvvvvvvvvutkK
....KtuuvvffffffffvvvvvvvvvvvuutK
......KtuuvvfffffvvvvvvvvvvvuutK
.......KtuuvvffffvvvvvvvvvvuutK
.........KttuvvvvvvvvvvvvuuttK
............KttuuuvvvvuuuttK
...............KKttttttttKK
...................KKKKKK
]])
-- Ears are attached, partly veiled by side locks.
map(34,32,[[
.KKKK
KtuukK
Kvtkuk
KvtukK
.KttK
..KK
]])
-- Both blue-grey eyes have a two-by-two catchlight, seven rows tall.
map(44,32,[[
.IIIIIIII
IOiOOibIN
.OiOOinIN
.OiibInIN
.OijibnIN
..bjjibI.
...bbb..
]])
map(62,32,[[
.IIIIII
IOOOinI
.OiOInI
.OibInI
.OijbnI
..bjjI.
...bb..
]])
map(45,30,[[
hsssh
]])
map(63,30,[[
hssh
]])
map(43,40,[[
rRRr
.rr
]])
map(64,39,[[
rRRr
.rr
]])
map(60,39,[[
.uu
..t
]])
map(58,43,[[
Kkk
.uv
]])

layer('06 Crown - broad silver bangs and locks')
map(22,3,[[
..................hhhhhhhhhhhhhhhhhhhhhh
..............hhhhssmmmmmmmmmmmmmmmmmmsshhh
...........hhhssmmmmllllllllllllllllllmmmmshh
.........hhssmmmlllllwwwwwwllllllllllllmmmmsshH
.......hhssmmllllwwwwwwwwwwwwwlllllllllllmmmsshH
......hssmmllllwwwwwwwwwwwwwwwwllllllwllllmmmsshH
.....hssmmlllwwwwwwwwwwwwwwwwwwwllllllwllllmmmsshH
....hssmmlllwwwwwwwwwwwwwwwwwwwwllllllwwllllmmsshH
...hssmllllwwwwwwwwwwwwwwwwwwwwwwllllllwwllllmmsshH
..hssmllllwwwwwwwwwwwwwwwwwwwwllllllllllwwwlllmmsshH
..hsmllllwwwwwwwwwwwwwwwwwwwllllmmlllllllllllllmmsshH
.hsmllllwwwwwwwwwwwwwwwwwwllllmmssmllllllmlllllmmsshH
.hsmlllwwwwwwwwwwwwwwwwwllllmmsshhssllllllmlllllmmsshH
hsmlllwwwwwwwwwwwwwwwwllllmmsshhsmhsllllllsmllllmmsshH
hsmlllwwwwwwwwwwwwwwwllllmmshhssmlmhsllllllsmllllmmsshH
hsmlllwwwwwwwwwwwwwwllllmmshhssmllmhsllllllsmllllmmsshH
hsmlllwwwwwwwwwwwwwllllmmshhssmlllmmhsllllllsmllllmmsshH
hsmlllwwwwwwwwwwwwllllmmshhssmllllmmhsllllllsmllllmmsshH
hsmlllwwwwwwwwwwwllllmmshhssmlllllmmhsllllllsmllllmmsshH
hsmlllwwwwwwwwwlllllmmshhssmllllllmmhsllllllsmllllmmsshH
hsmlllwwwwwwwwlllllmmshhssmlllllllmmhsllllllsmllllmmsshH
hsmlllwwwllllllmmshhssmllllmmshH
hsmlllwwllllllmmshhssmlllmmshH
hsmlllwwlllllmmshhssmllmmshH
hsmlllwwllllmmshhssmlmmshH
hsmlllwwlllmmshhssmmshH
hsmlllwwllmmshhssmshH
hsmlllwwlmmshhsmshH
hsmlllwwmmshhsmshH
HsmlllwwlmssmmlhH
HsmlllwwlmssmmlhH
HsmlllwwlmssmmlhH
HsmlllwwlmssmmlhH
HsmlllwwlmssmmlhH
HsmlllwwlmssmmlhH
HsmlllwwlmssmmlhH
HsmlllwwlmssmmlhH
.HslllwwlmssmmlhH
.HslllwwlmssmmlhH
.HslllwwlmssmmlhH
.HslllwwlmssmmlhH
..HsllwwlmssmmlhH
..HsllwwlmssmmlhH
..HsllwllmssmmlhH
..HsllwllmssmmlhH
...HslwllmssmmlhH
...HslwllmssmmlhH
....HslwllmssmlhH
....HslwllmssmlhH
.....HslwllmsmlhH
......HslwllmmlhH
.......HslwllmlhH
........HslwlmhH
.........HslmhH
..........HshH
...........HH
]])
map(60,24,[[
hmllllllllmmsshH
.hmlllllllmmsshH
..hmllllllmmsshH
...hmlllllmmsshH
....hmllllmmsshH
.....hslllmmsshH
......hsllmmsshH
.......hsllmmshH
........hsllmshH
.........hsllmshH
.........HsllmshH
.........HsllmshH
.........HsllmshH
.........HsllmshH
.........HsllmshH
.........HsllmshH
.........HsllmshH
.........HsllmshH
.........HsllmshH
.........HsllmshH
.........HsllmshH
..........HsllmshH
..........HsllmshH
..........HsllmshH
..........HsllmshH
..........HsllmshH
..........HsllmshH
...........HslmshH
...........HslmshH
...........HslmshH
............HsmshH
............HsmshH
.............HshH
..............HH
]])

map(58,22,[[
lllmshH
.lllmshH
..lllmshH
...llmshH
...llmshH
...llmshH
...lmshH
...mshH
..mshH
..shH
...H
]])
-- Crown strand glints and a short parting shadow; all clusters are attached.
map(29,9,[[
...................llmm
................llmmm
.............lllmmm
..........llllmmm
........llllmm
.....llllmmm
...llllmmm
.llllmmm
lllmmm
llmmm
lmmm
]])
map(57,8,[[
mmss
llmss
.llmss
..llmss
...llmss
....llmss
.....llmss
......llmss
.......llmss
........llmss
.........llmss
..........llms
...........lms
............ms
]])

layer('07 Oversized gloves - four fingers padded palms')
map(30,59,[[
.....NNNNNNNN
....NnbcccbbnN
....NbgGGGgbnN
....NbglwlgbnN
...NbbgggggbbnN
..Hssllwlllmmssn
.Hllwwllccccllmn
HlwwwwlcbGGbclmn
HlwwwHlcglGbcmln
HlwwH.wlcGbcmlmn
HlmH.Hwlccclmlmn
.nn..Hwlblwblwlmn
.....Hwlblwblwlmn
.....Hlmblmblmlmn
......nn.nn.nn.nn
]])
map(64,55,[[
....NNNNNN
...NnbccbnN
...NbgGGgbnN
...NbglwgbnN
..NbbggggbbnN
.Hssllwwlmssn
Hllwwllcbcllmn
HlwwwlcbGGbclmn
HlwwHlcglGbcmln
HlmH.wlcGbcmlmn
.nn.Hwlcccllmn
....Hwlblwblmn
....Hwlblwblmn
....Hlmblmblmn
.....nn.nn.nn
]])

layer('08 Hair jewellery - blue blossom and tassel')
map(21,13,[[
.....nnn
....ngGgn
...nglncn
...nglncn.nn
..nngncnbnggn
.ngGnnnbnglgn
nglcncbnblgn
ngccbdcbccn
.nncdeedcn
..nbdedbnn
.ngnbbbnggn
nglgnnnglgn
nggcn.nggn
.nnnn..nn
...nn
..nbcn
..ncdn
...nn
...gn
..nbcn
..ncdn
...nn
..nbcn
..nbcdn
..nbcdn
..nbcdn
..nbcdn
..nbcdn
..nbcdn
..ncbn
...nn
]])
-- Coral accent hanging from shoulder strap and a tiny belt ornament.
map(40,56,[[
gg
gn
pp
pC
pC
pC
pC
pp
]])
map(64,72,[[
.gg
gGGg
gllg
.gg
.pp
pCCp
pCCp
pCCp
.pp
]])

spr:saveAs('base.aseprite')
spr:saveCopyAs('base.png')
local pass=app.params['pass'] or '01'
spr:saveCopyAs('scripts/pass_'..pass..'.png')
print('Rendered base.aseprite and base.png; pass '..pass)
