from pathlib import Path
p=Path('scripts/draw.lua'); s=p.read_text(encoding='utf-8')
start=s.index('map(22,3,[['); end=s.index("layer('07 Oversized",start)
old=s[start:].split('[[',1)[1].split(']]',1)[0].strip().splitlines()
crown=old[:21]  # y=3..23, the broad crown is preserved.
crown += '''hsmlllwwwllllllmmshhssmllllmmshH
hsmlllwwllllllmmshhssmlllmmshH
hsmlllwwlllllmmshhssmllmmshH
hsmlllwwllllmmshhssmlmmshH
hsmlllwwlllmmshhssmmshH
hsmlllwwllmmshhssmshH
hsmlllwwlmmshhsmshH
hsmlllwwmmshhsmshH
hsmlllwwmshhsmshH
hsmlllwwmshhsmshH
hsmlllwwmshhsmshH
hsmlllwwmshhsmshH
hsmlllwwmshhsmshH
hsmlllwwmshhsmshH
hsmlllwwmshhsmshH
hsmlllwwmshhsmshH
hsmlllwwmshhsmshH
hsmlllwwmshhsmshH
hsmlllwwmshhsmshH
.HslllwwmshhsmshH
.HslllwwmshhsmshH
.HslllwwmshhsmshH
.HslllwwmshhsmshH
..HslllwmsHhsmshH
..HslllwmsHhsmshH
..HslllwmsHhsmshH
...HsllwmsHhsmshH
...HsllwmsHhsmshH
....HslwmsHhsmshH
....HslwmsHhsmshH
.....HslmsHhsmshH
......HsmsHhsmshH
.......HssHHsshH
........HH..HHH'''.splitlines()
# Right fringe rows are individually positioned; long lock follows cheek.
right='''map(60,24,[[
hmllllllllmmsshH
.hmlllllllmmsshH
..hmllllllmmsshH
...hmlllllmmsshH
....hmllllmmsshH
.....hslllmmsshH
......hsllmmsshH
.......hsllmmshH
........hsllmshH
.........hsllmshH
.........HsllmshH
.........HsllmshH
.........HsllmshH
.........HsllmshH
.........HsllmshH
.........HsllmshH
.........HsllmshH
.........HsllmshH
.........HsllmshH
.........HsllmshH
.........HsllmshH
..........HsllmshH
..........HsllmshH
..........HsllmshH
..........HsllmshH
..........HsllmshH
..........HsllmshH
...........HslmshH
...........HslmshH
...........HslmshH
............HsmshH
............HsmshH
.............HshH
..............HH
]])
'''
s=s[:start]+'map(22,3,[[\n'+'\n'.join(crown)+'\n]])\n'+right+'\n'+s[end:]
start=s.index('-- Near eye:');end=s.index("layer('06 Crown",start)
s=s[:start]+'''-- Both blue-grey eyes have a two-by-two catchlight, seven rows tall.
map(44,32,[[
.IIIIIIII
IOiOOibIN
.OiOOibIN
.OiijibIN
.OiijibIN
..bjjibI.
...bbb..
]])
map(62,32,[[
.IIIIII
IOiOOIn
.OiOOIn
.OiibIn
.OijbIn
..bjjI.
...bb..
]])
map(45,30,[[
hsssh
]])
map(63,30,[[
hssh
]])
map(43,40,[[
rRRr
.rr
]])
map(66,40,[[
rRr
.r
]])
map(60,39,[[
.uu
..t
]])
map(58,43,[[
ktt
.uv
]])

''' +s[end:]
start=s.index('map(33,85,[[');end=s.index("layer('04 Torso",start)
s=s[:start]+'''map(35,85,[[
.....NllmbnN
.....NlwlbnN
....NlwmlbnN
...NlwlclbnN
..NwwlcbblnN
.NwwllcllbnN
NwwwwwllmbnN
NmmllllmmbnN
.NNNNNNNNNN
]])
map(54,85,[[
.NllmbbnN
.NlwlbbnN
.NlwlmbnN
.NlwllmbnNN
.NlwwlmblmlN
.NlwwwlmwwllN
..NwwwwllwwlmN
..NmlllllmmmsN
...NNNNNNNNNN
]])

''' +s[end:]
start=s.index("layer('07 Oversized");end=s.index("layer('08 Hair jewellery",start)
s=s[:start]+'''layer('07 Oversized gloves - four fingers padded palms')
map(30,59,[[
.....NNNNNNNN
....NnbbbbbbnN
....NbgGGGgbnN
....NbglwlgbnN
....NNgggggNNN
...HsslllllmssH
..HmlwlllllllmsH
.HllwwlcbbcclmsH
HlwwwlcgGGbcclmH
HlwwwlcglGgcclmH
HlwwHllcgGcclmsH
HlmH.lllcccllmsH
.HH.HlwlllmllmsH
....HlwlHlmHlmsH
....HlmH.HmH.HmH
.....HH...H...H
]])
map(64,55,[[
....NNNNNN
...NnbbbbnN
...NbgGGgbnN
...NbglwgbnN
...NNggggNNN
..HsmlllmssHH
.HsllwwlllmsH
HlwwwlcbbclmsH
HlwwwcgGGbclmsH
HlwwlcglGgcclmH
HlmHllcgGcclmsH
.HHllwlclllmsH
...HlwlHlmHlmsH
...HlmH.HmH.HmH
....HH...H...H
]])

''' +s[end:]
p.write_text(s,encoding='utf-8')
