local pc=app.pixelColor
local im=Image{fromFile='base.png'}
local colors,alphas={},{} local count=0 local x0,y0,x1,y1=64,64,-1,-1
local isolated={} local opaque={}
for y=0,63 do for x=0,63 do
 local p=im:getPixel(x,y) local a=pc.rgbaA(p)
 alphas[a]=true
 if a>0 then
  opaque[y*64+x]=true count=count+1 colors[p]=true
  x0=math.min(x0,x) y0=math.min(y0,y) x1=math.max(x1,x) y1=math.max(y1,y)
 end
end end
for y=0,63 do for x=0,63 do if opaque[y*64+x] then
 local n=0
 for dy=-1,1 do for dx=-1,1 do
  if (dx~=0 or dy~=0) and x+dx>=0 and x+dx<64 and y+dy>=0 and y+dy<64 and opaque[(y+dy)*64+x+dx] then n=n+1 end
 end end
 if n==0 then isolated[#isolated+1]={x,y} end
end end end
local seen={} local components={}
for k in pairs(opaque) do if not seen[k] then
 local q={k} seen[k]=true local head=1 local size=0
 while head<=#q do
  local v=q[head] head=head+1 size=size+1
  local x,y=v%64,math.floor(v/64)
  for dy=-1,1 do for dx=-1,1 do
   local xx,yy=x+dx,y+dy local n=yy*64+xx
   if xx>=0 and xx<64 and yy>=0 and yy<64 and opaque[n] and not seen[n] then seen[n]=true q[#q+1]=n end
  end end
 end
 components[#components+1]=size
end end
table.sort(components,function(a,b) return a>b end)
local nc=0 for _ in pairs(colors) do nc=nc+1 end
local validAlpha=true for a in pairs(alphas) do if a~=0 and a~=255 then validAlpha=false end end
local reopened=app.open('base.aseprite')
local rendered=Image(64,64,ColorMode.RGB) rendered:drawSprite(reopened,1)
local mismatch=0
for y=0,63 do for x=0,63 do if rendered:getPixel(x,y)~=im:getPixel(x,y) then mismatch=mismatch+1 end end end
local preview=Image{fromFile='preview_8x.png'} local previewErrors=0
for y=0,511 do for x=0,511 do
 local expected=im:getPixel(math.floor(x/8),math.floor(y/8))
 if pc.rgbaA(expected)==0 then expected=pc.rgba(128,128,128,255) end
 if preview:getPixel(x,y)~=expected then previewErrors=previewErrors+1 end
end end
local lines={
 'MIRKA - native base sprite verification',
 'Generated by Aseprite 1.3.18 Lua; coordinates are zero-based and inclusive.',
 'Canvas: '..im.width..'x'..im.height,
 'Visible opaque RGB colours: '..nc..' (limit 32)',
 'RGBA entries including transparent: '..(nc+1),
 'Alpha values: 0, 255; binary alpha: '..tostring(validAlpha),
 string.format('Opaque bounding box: (%d,%d)-(%d,%d)',x0,y0,x1,y1),
 string.format('Bounding dimensions: %dx%d; character height: %d px',x1-x0+1,y1-y0+1,y1-y0+1),
 'Feet baseline: y='..y1,
 'Opaque pixels: '..count,
 'Isolated opaque pixels (8-neighbour test): '..#isolated,
 'Opaque connected components (8-neighbour): '..#components..' ['..table.concat(components,', ')..']',
 'Reopened .aseprite composite versus base.png: '..mismatch..' different pixels',
 'Exact 8x nearest-neighbour preview: '..previewErrors..' different pixels',
 'One frame; no ball; transparent canvas. Hidden sampled-draft reference layer retained.',
 'Preview: 512x512 nearest-neighbour enlargement on #808080.',
 'Style QA: 28 px ears/head region, 22 px petite body; both amber eyes visible;',
 '1 px glints and fang, wide bob highlight, cream/mint/plum jacket, striped tail and socks.',
 'No gradients or dithering in final. Detail pixels inside connected shapes (eye glints,',
 'fang, jewellery) are intentional; no detached single-pixel particles.',
 'Known issues: no technical issues found. Fine costume embroidery is intentionally simplified.',
 'Method: built-in imagegen once with both references; Aseprite cell sampling followed',
 'by extensive native-pixel redraw in semantic layers. See scripts/draft_prompt.txt.'
}
local passed=im.width==64 and im.height==64 and nc<=32 and validAlpha and y1>=60 and y1<=61 and y1-y0+1>=44 and y1-y0+1<=50 and #isolated==0 and #components==1 and mismatch==0 and previewErrors==0
lines[#lines+1]='OVERALL: '..(passed and 'PASS' or 'FAIL')
local f=io.open('verification.txt','w') f:write(table.concat(lines,'\n')..'\n') f:close()
print(table.concat(lines,'\n'))

-- Comparison: left original illustration; middle exact 8x sprite;
-- right two style references cropped from the supplied sheet.
local comp=Image(1200,592,ColorMode.RGB) comp:clear(pc.rgba(226,226,226,255))
local source=Image{fromFile='source.png'} source:resize{width=341,height=512}
comp:drawImage(source,Point(8,56))
comp:drawImage(Image{fromFile='preview_8x.png'},Point(357,56))
local r1=Image{fromFile='scripts/reference_crop_1.png'} r1:resize{width=195,height=230}
local r2=Image{fromFile='scripts/reference_crop_3.png'} r2:resize{width=233,height=237}
comp:drawImage(r1,Point(923,56)) comp:drawImage(r2,Point(904,324))
-- Compact 3x5 bitmap labels, drawn entirely with the Lua API.
local glyph={A={'010','101','111','101','101'},B={'110','101','110','101','110'},C={'011','100','100','100','011'},E={'111','100','110','100','111'},F={'111','100','110','100','100'},G={'011','100','101','101','011'},I={'111','010','010','010','111'},K={'101','101','110','101','101'},L={'100','100','100','100','111'},M={'101','111','111','101','101'},N={'101','111','111','111','101'},O={'010','101','101','101','010'},P={'110','101','110','100','100'},R={'110','101','110','101','101'},S={'011','100','010','001','110'},T={'111','010','010','010','010'},U={'101','101','101','101','111'},V={'101','101','101','101','010'},X={'101','101','010','101','101'},Y={'101','101','010','010','010'},['8']={'111','101','111','101','111'},[' ']={'000','000','000','000','000'}}
local function label(text,x,y)
 for k=1,#text do local g=glyph[text:sub(k,k)] or glyph[' ']
  for yy=1,5 do for xx=1,3 do if g[yy]:sub(xx,xx)=='1' then
   for dy=0,2 do for dx=0,2 do comp:putPixel(x+(k-1)*12+(xx-1)*3+dx,y+(yy-1)*3+dy,pc.rgba(60,52,65,255)) end end
  end end end
 end
end
label('SOURCE',32,24) label('MIRKA NATIVE X8',387,24) label('STYLE CROPS',923,24)
comp:saveAs('compare.png')
assert(passed,'Sprite verification failed')
